"use client"
import './globals.css'
import type { Metadata } from 'next'
import { TopHeader } from '@/components/TopHeader'
import { Header } from '@/components/Header'
import { Footer } from '@/components/Footer'
import ReduxProvider from '@/redux/Provider'
import { Spin } from 'antd';
import { SessionProvider } from "next-auth/react";

// import { Inter } from 'next/font/google'

// const inter = Inter({ subsets: ['latin'] })

// export const metadata: Metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app',
// }

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {


  return (
    <html lang="en">
      <body>
        <div>
          <ReduxProvider>
            <SessionProvider>
              <Spin
                tip="Loading..."
                spinning={false}
              >
                <TopHeader />
                <Header />
                <hr />
                {children}
                <Footer />
              </Spin>
            </SessionProvider>
          </ReduxProvider>
        </div>
      </body>
    </html>
  )
}
